#!/usr/bin/env python3
"""Generate OpenSpec delta specs for each change from the canonical specs.

Usage:  python3 openspec/tools/gen-deltas.py [--check]

Each change's proposal.md lists the requirement IDs it delivers under a
"## Requirements delivered" heading, one per bullet, e.g. "- FLS-01".
This tool extracts the matching "### Requirement: … [ID]" blocks (header,
body and scenarios) from openspec/specs/<capability>/spec.md and writes
openspec/changes/<change>/specs/<capability>/spec.md with an
"## ADDED Requirements" section, which is what `openspec validate` expects.

--check exits non-zero if any canonical requirement is delivered by no
change or by more than one change, or if a proposal references an unknown
ID. It never writes files.
"""
import os, re, sys, glob

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SPECS = os.path.join(ROOT, 'specs')
CHANGES = os.path.join(ROOT, 'changes')

PREFIX_TO_CAP = {}
REQ_RE = re.compile(r'^### Requirement: (.+?) \[([A-Z]{3})-(\d{2})\]\s*$', re.M)

def load_specs():
    """Return {ID: (capability_dir, title, block_text)} and {cap: title}."""
    reqs, titles = {}, {}
    for spec in sorted(glob.glob(os.path.join(SPECS, '*', 'spec.md'))):
        cap = os.path.basename(os.path.dirname(spec))
        text = open(spec, encoding='utf-8').read()
        m = re.search(r'^# (.+?) Specification\s*$', text, re.M)
        titles[cap] = m.group(1) if m else cap
        # split into blocks at every "### Requirement" header; a block ends at
        # the next "### " or "## " heading or "---" rule.
        positions = [(mm.start(), mm) for mm in REQ_RE.finditer(text)]
        for i, (start, mm) in enumerate(positions):
            end = len(text)
            nxt = re.search(r'^(### |## |---\s*$)', text[mm.end():], re.M)
            if nxt:
                end = mm.end() + nxt.start()
            block = text[start:end].rstrip() + '\n'
            rid = f'{mm.group(2)}-{mm.group(3)}'
            if rid in reqs:
                sys.exit(f'duplicate requirement id {rid} in {spec}')
            PREFIX_TO_CAP[mm.group(2)] = cap
            reqs[rid] = (cap, mm.group(1), block)
    return reqs, titles

def load_changes():
    """Return {change_dir: [IDs]} from each proposal.md."""
    out = {}
    for prop in sorted(glob.glob(os.path.join(CHANGES, '*', 'proposal.md'))):
        change = os.path.basename(os.path.dirname(prop))
        text = open(prop, encoding='utf-8').read()
        m = re.search(r'^## Requirements delivered\s*$(.*?)(?=^## |\Z)', text, re.M | re.S)
        ids = re.findall(r'^\s*-\s*\**([A-Z]{3}-\d{2})\**', m.group(1), re.M) if m else []
        out[change] = ids
    return out

def main():
    check = '--check' in sys.argv
    reqs, titles = load_specs()
    changes = load_changes()
    delivered = {}
    errors = []
    for change, ids in changes.items():
        for rid in ids:
            if rid not in reqs:
                errors.append(f'{change}: unknown requirement {rid}')
                continue
            delivered.setdefault(rid, []).append(change)
    for rid in reqs:
        who = delivered.get(rid, [])
        if not who:
            errors.append(f'{rid} is delivered by no change')
        elif len(who) > 1:
            errors.append(f'{rid} is delivered by several changes: {who}')
    if check:
        for e in errors:
            print('ERROR', e)
        print(f'{len(reqs)} requirements, {len(changes)} changes, {len(errors)} problems')
        sys.exit(1 if errors else 0)
    for change, ids in changes.items():
        by_cap = {}
        for rid in ids:
            if rid in reqs:
                cap, _, block = reqs[rid]
                by_cap.setdefault(cap, []).append(block)
        # remove stale generated deltas
        for old in glob.glob(os.path.join(CHANGES, change, 'specs', '*', 'spec.md')):
            os.remove(old)
        for cap, blocks in by_cap.items():
            d = os.path.join(CHANGES, change, 'specs', cap)
            os.makedirs(d, exist_ok=True)
            with open(os.path.join(d, 'spec.md'), 'w', encoding='utf-8') as f:
                f.write(f'# {titles[cap]} (delta for {change})\n\n')
                f.write('<!-- GENERATED by openspec/tools/gen-deltas.py from openspec/specs/'
                        f'{cap}/spec.md. Do not edit. -->\n\n')
                f.write('## ADDED Requirements\n\n')
                f.write('\n'.join(blocks))
    for e in errors:
        print('WARNING', e)
    print(f'generated deltas for {len(changes)} changes covering {len(delivered)} of {len(reqs)} requirements')

if __name__ == '__main__':
    main()
